# Generated by Django 5.1.3 on 2024-12-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos_Ventas', '0002_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.CharField(default='https://img.com', max_length=100),
            preserve_default=False,
        ),
    ]
